schemaVersion: "2.0.0"

metadataTest:
  workdir: "/home/devops"
  entrypoint: ["/bin/bash", "--init-file", "/home/devops/.bashrc-ni"]

commandTests:
  - name: "current user"
    command: "whoami"
    expectedOutput: ["devops"]

  - name: "terraform installation"
    command: "terraform"
    args: ["--help"]
    expectedOutput: ["Usage: terraform.*"]

  - name: "Calico CLI installation"
    command: "calicoctl"
    args: ["--help"]
    expectedOutput: ["Usage:\n.*calicoctl.*"]

  - name: "IBM Cloud CLI installation"
    command: "ibmcloud"
    args: ["--help"]
    expectedOutput: ["NAME:\n.*ibmcloud.*"]

  - name: "IBM Cloud container-service plugin"
    command: "ibmcloud"
    args: ["plugin", "list"]
    expectedOutput: [".*container-service/kubernetes-service.*"]

  - name: "IBM Cloud container-registry plugin"
    command: "ibmcloud"
    args: ["plugin", "list"]
    expectedOutput: [".*container-registry.*"]

  - name: "IBM Cloud cloud-databases plugin"
    command: "ibmcloud"
    args: ["plugin", "list"]
    expectedOutput: [".*cloud-databases.*"]

  - name: "Kubectl CLI installation"
    command: "kubectl"
    args: ["--help"]
    expectedOutput: ["kubectl.*"]

  - name: "Helm CLI installation"
    command: "helm"
    args: ["--help"]
    expectedOutput: ["The Kubernetes package manager.*"]

  - name: "Kustomize CLI installation"
    command: "kustomize"
    args: ["--help"]
    expectedOutput: [".*Usage:\n  kustomize.*"]

  - name: "Git installation"
    command: "git"
    args: ["--help"]
    expectedOutput: ["usage: git.*"]

  # - name: "Postgres installation"
  #   command: "createdb"
  #   args: ["--help"]
  #   expectedOutput: ["createdb creates a PostgreSQL database.*"]

  - name: "OpenShift client installation"
    command: "oc"
    args: ["--help"]
    expectedOutput: [".*OpenShift.*"]

  - name: "python"
    command: "python"
    args: ["--help"]
    expectedOutput: [".*python.*"]

  - name: "pip"
    command: "pip"
    args: ["--help"]
    expectedOutput: [".*pip.*"]

  - name: "ansible"
    command: "/home/devops/.local/bin/ansible-playbook"
    args: ["--help"]
    expectedOutput: [".*ansible.*"]

#  - name: "nvm installation"
#    setup: [["/bin/bash", "--init-file", "/home/devops/.bashrc-ni"]]
#    command: "nvm"
#    args: ["--help"]
#    expectedOutput: [".*Node Version Manager.*"]

#  - name: "node installation"
#    command: "node"
#    args: ["--help"]
#    expectedOutput: ["v\\d\\d[.]\\d\\d[.]\\d\n"]

#  - name: "yo installation"
#    command: "yo"
#    args: ["--help"]
#    expectedOutput: ["\\d[.]\\d[.]\\d\n"]

fileExistenceTests:
  - name: 'jenkins-config-template.xml'
    path: '/home/devops/etc'
    shouldExist: true

  - name: "terraform-provider-helm.*"
    path: "/home/devops/.terraform.d/plugins"
    shouldExist: true

  - name: "terraform-provider-kubernetes.*"
    path: "/home/devops/.terraform.d/plugins"
    shouldExist: true

  - name: "terraform-provider-ibm.*"
    path: "/home/devops/.terraform.d/plugins"
    shouldExist: true

  - name: 'cluster-pull-secret-apply.sh'
    path: '/usr/local/bin'
    shouldExist: true

  - name: 'setup-namespace-pull-secrets.sh'
    path: '/usr/local/bin'
    shouldExist: true

  - name: 'checkPodRunning.sh'
    path: '/usr/local/bin'
    shouldExist: true
